apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: perc-webserver-test
spec:
  replicas: 3
  selector:
    matchLabels:
      service: http-webserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 1
  template:
    metadata:
      labels:
        service: http-webserver
    spec:
      containers:
      - name: perc
        image: harnit/percolator-webserver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: SF_TOKEN
            value: "<SET TOKEN>"
        lifecycle:
          preStop:
            exec:
              command: ["sleep","5"]
